// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHVt8ErVIPr79J9ubPOmJgWU3S58bzgI',
    appId: '1:508271595505:web:0d585122e64331ba0a3e50',
    messagingSenderId: '508271595505',
    projectId: 'flutter-app-cab3a',
    authDomain: 'flutter-app-cab3a.firebaseapp.com',
    storageBucket: 'flutter-app-cab3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbfs9e-Usk1XaQl_F254S_MvS-bgOFOdM',
    appId: '1:508271595505:android:4fc0a427ab95f5c70a3e50',
    messagingSenderId: '508271595505',
    projectId: 'flutter-app-cab3a',
    storageBucket: 'flutter-app-cab3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjf9v5YkT6-83AS5NERbJOSt9uamu40LI',
    appId: '1:508271595505:ios:9eb1de18deeb994c0a3e50',
    messagingSenderId: '508271595505',
    projectId: 'flutter-app-cab3a',
    storageBucket: 'flutter-app-cab3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterGame',
  );
}
